import { GoogleGenAI, Type } from '@google/genai';
import { LevelData, EntityType } from '../types';

export const generateLevel = async (promptTheme: string): Promise<LevelData | null> => {
  // SECURITY: Ensure API Key is present. 
  // This prevents the app from attempting requests if the key is missing (e.g. in public demos without env vars).
  if (!process.env.API_KEY) {
    console.error("API Key is missing. Please set process.env.API_KEY.");
    return null;
  }

  // Initialize client with the key from environment
  const genAI = new GoogleGenAI({ apiKey: process.env.API_KEY });
  const model = "gemini-2.5-flash";
  
  const systemInstruction = `
    You are a professional Level Designer for a 2D Platformer game like Mario. 
    Your task is to generate a playable level layout in JSON format.
    The coordinate system starts at (0,0) top-left. Ground level is typically around y=500. 
    The player jumps about 150 pixels high and 200 pixels far.
    Do not make the level impossible.
    The level should have a length of about 2000-3000 pixels width.
    Use platforms, enemies, and coins.
    Goal should be at the far right.
  `;

  const prompt = `Generate a level with the theme: "${promptTheme}".`;

  try {
    const response = await genAI.models.generateContent({
      model: model,
      contents: prompt,
      config: {
        systemInstruction: systemInstruction,
        responseMimeType: "application/json",
        maxOutputTokens: 4000, // COST CONTROL: Limit output size to prevent excessive token usage
        responseSchema: {
          type: Type.OBJECT,
          properties: {
            name: { type: Type.STRING },
            description: { type: Type.STRING },
            theme: {
              type: Type.OBJECT,
              properties: {
                background: { type: Type.STRING, description: "Hex color" },
                platformColor: { type: Type.STRING, description: "Hex color" },
                accentColor: { type: Type.STRING, description: "Hex color" }
              }
            },
            platforms: {
              type: Type.ARRAY,
              items: {
                type: Type.OBJECT,
                properties: {
                  x: { type: Type.NUMBER },
                  y: { type: Type.NUMBER },
                  w: { type: Type.NUMBER },
                  h: { type: Type.NUMBER },
                  type: { type: Type.STRING, enum: ["solid", "oneway"] }
                },
                required: ["x", "y", "w", "h", "type"]
              }
            },
            enemies: {
              type: Type.ARRAY,
              items: {
                type: Type.OBJECT,
                properties: {
                  x: { type: Type.NUMBER },
                  y: { type: Type.NUMBER },
                  type: { type: Type.STRING, enum: ["WALKER", "FLYER"] },
                  patrolRange: { type: Type.NUMBER, description: "Total distance to patrol" }
                },
                required: ["x", "y", "type"]
              }
            },
            coins: {
               type: Type.ARRAY,
               items: {
                 type: Type.OBJECT,
                 properties: {
                   x: { type: Type.NUMBER },
                   y: { type: Type.NUMBER },
                 },
                 required: ["x", "y"]
               }
            }
          },
          required: ["name", "theme", "platforms", "enemies", "coins"]
        }
      }
    });

    const rawData = JSON.parse(response.text || "{}");
    
    // SAFETY: Robust fallback values to prevent crashes if AI returns incomplete data
    const safeTheme = rawData.theme || {};
    const finalTheme = {
        background: safeTheme.background || '#333',
        platformColor: safeTheme.platformColor || '#555',
        accentColor: safeTheme.accentColor || '#777'
    };

    // Map raw AI response to our strong types
    const levelData: LevelData = {
      id: `ai-${Date.now()}`,
      name: rawData.name || "AI Generated Level",
      description: rawData.description || "A unique challenge generated by Gemini.",
      theme: finalTheme,
      playerStart: { x: 50, y: 400 }, // Safe default
      goal: { x: 2000, y: 400, w: 50, h: 150 }, // Default goal
      platforms: (rawData.platforms || []).map((p: any, i: number) => ({
        ...p,
        id: i,
        color: finalTheme.platformColor
      })),
      enemies: (rawData.enemies || []).map((e: any, i: number) => ({
        id: i,
        x: e.x,
        y: e.y,
        w: 40,
        h: e.type === "FLYER" ? 30 : 40,
        type: e.type === "FLYER" ? EntityType.ENEMY_FLYER : EntityType.ENEMY_WALKER,
        vx: 2,
        vy: 0,
        patrolStart: e.x - (e.patrolRange || 100) / 2,
        patrolEnd: e.x + (e.patrolRange || 100) / 2
      })),
      coins: (rawData.coins || []).map((c: any, i: number) => ({
        id: i,
        x: c.x,
        y: c.y,
        w: 20,
        h: 20,
        collected: false
      }))
    };

    // Auto-place goal at the end of the furthest platform
    let maxX = 0;
    levelData.platforms.forEach(p => {
      if (p.x + p.w > maxX) maxX = p.x + p.w;
    });
    
    // Only update goal if we actually have platforms
    if (maxX > 0) {
        levelData.goal.x = maxX - 100;
        // Ensure goal isn't in the sky if there's no platform
        const goalPlat = levelData.platforms.find(p => p.x <= levelData.goal.x && p.x + p.w >= levelData.goal.x);
        if(goalPlat) {
            levelData.goal.y = goalPlat.y - levelData.goal.h;
        }
    }

    return levelData;

  } catch (error) {
    console.error("Gemini Level Generation Failed", error);
    // Return null so the UI can handle it gracefully without crashing
    return null;
  }
};